# Generated by Django 4.2.25 on 2025-11-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_collection_is_active_item_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="hidden_fields",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
