# Generated by Django 4.2.25 on 2025-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_item_hidden_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="for_sale",
            field=models.BooleanField(default=False),
        ),
    ]
