# Generated by Django 4.2.25 on 2025-12-05 19:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collection", "0004_item_for_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("item", "Item"),
                            ("collection", "Collection"),
                            ("custom", "Custom / external"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Display label", max_length=255)),
                ("external_url", models.URLField(blank=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="collection.collection",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="collection.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "kind"], name="collection__user_id_768a39_idx"),
                    models.Index(
                        fields=["user", "created_at"], name="collection__user_id_ff3480_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item__isnull", False)),
                fields=("user", "item"),
                name="favorite_unique_item_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("collection__isnull", False)),
                fields=("user", "collection"),
                name="favorite_unique_collection_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("collection__isnull", True), ("item__isnull", False), ("kind", "item")
                    ),
                    models.Q(
                        ("collection__isnull", False),
                        ("item__isnull", True),
                        ("kind", "collection"),
                    ),
                    models.Q(
                        ("collection__isnull", True), ("item__isnull", True), ("kind", "custom")
                    ),
                    _connector="OR",
                ),
                name="favorite_kind_matches_target",
            ),
        ),
    ]
