# Generated by Django 4.2.25 on 2025-12-10 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0005_favorite_favorite_favorite_unique_item_per_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='WishList',
        ),
        migrations.RenameIndex(
            model_name='wishlist',
            new_name='collection__user_id_556996_idx',
            old_name='collection__user_id_768a39_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlist',
            new_name='collection__user_id_1b2ee8_idx',
            old_name='collection__user_id_ff3480_idx',
        ),
    ]
