# Generated by Django 4.2.25 on 2025-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0006_rename_favorite_wishlist_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wishlist",
            name="favorite_unique_item_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="wishlist",
            name="favorite_unique_collection_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="wishlist",
            name="favorite_kind_matches_target",
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item__isnull", False)),
                fields=("user", "item"),
                name="wishlist_unique_item_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("collection__isnull", False)),
                fields=("user", "collection"),
                name="wishlist_unique_collection_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("collection__isnull", True), ("item__isnull", False), ("kind", "item")
                    ),
                    models.Q(
                        ("collection__isnull", False),
                        ("item__isnull", True),
                        ("kind", "collection"),
                    ),
                    models.Q(
                        ("collection__isnull", True), ("item__isnull", True), ("kind", "custom")
                    ),
                    _connector="OR",
                ),
                name="wishlist_kind_matches_target",
            ),
        ),
    ]
