# Generated by Django 4.2.25 on 2025-12-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_remove_wishlist_favorite_unique_item_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_favorite",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="is_favorite",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
