# Generated by Django 4.2.25 on 2025-12-14 14:57

from django.db import migrations, models

import apps.collection.models.collection
import apps.collection.models.item


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0008_collection_is_favorite_item_is_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="preview_md",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=apps.collection.models.collection.collection_image_path,
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="preview_sm",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=apps.collection.models.collection.collection_image_path,
            ),
        ),
        migrations.AddField(
            model_name="itemimage",
            name="preview_md",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=apps.collection.models.item.item_image_path,
            ),
        ),
        migrations.AddField(
            model_name="itemimage",
            name="preview_sm",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=apps.collection.models.item.item_image_path,
            ),
        ),
    ]
