# Generated by Django 4.2.25 on 2025-12-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0009_collection_preview_md_collection_preview_sm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="item",
            name="current_value",
        ),
        migrations.RemoveField(
            model_name="item",
            name="extra",
        ),
        migrations.RemoveField(
            model_name="item",
            name="for_sale",
        ),
        migrations.RemoveField(
            model_name="item",
            name="hidden_fields",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_favorite",
        ),
        migrations.RemoveField(
            model_name="item",
            name="location",
        ),
        migrations.RemoveField(
            model_name="item",
            name="purchase_date",
        ),
        migrations.RemoveField(
            model_name="item",
            name="purchase_price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
    ]
