# Generated by Django 4.2.25 on 2025-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0010_remove_item_currency_remove_item_current_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="current_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="item",
            name="for_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="hidden_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="item",
            name="is_favorite",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
