# Generated by Django 4.2.25 on 2025-12-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0011_item_currency_item_current_value_item_extra_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together=set(),
        ),
    ]
