# Generated by Django 4.2.25 on 2025-12-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('type', models.CharField(choices=[('follow', 'Follow'), ('post', 'Post Create'), ('comment_create', 'Comment Create'), ('item_create', 'Item Create')], db_index=True, max_length=32)),
                ('is_checked', models.BooleanField(db_index=True, default=False)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['for_user', 'is_checked', '-created_at'], name='notificatio_for_use_e5a3f4_idx'), models.Index(fields=['for_user', '-created_at'], name='notificatio_for_use_09b2e4_idx')],
            },
        ),
    ]
