# Generated by Django 4.2.25 on 2025-12-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="info",
            field=models.JSONField(blank=True, default={}),
        ),
    ]
