# Generated by Django 4.2.25 on 2025-12-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
