# Generated by Django 4.2.25 on 2025-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Follow'), ('post', 'Post Create'), ('post_like', 'Post Like'), ('comment_create', 'Comment Create'), ('comment_like', 'Comment Like'), ('item_create', 'Item Create')], db_index=True, max_length=32),
        ),
    ]
