# Generated by Django 4.2.25 on 2025-11-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_pricechartingconnect'),
        ('collection', '0005_alter_item_pricecharting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricechartingIntegration',
        ),
        migrations.AddIndex(
            model_name='pricechartingconnect',
            index=models.Index(fields=['url'], name='games_price_url_7c705e_idx'),
        ),
    ]
