# Generated by Django 4.2.25 on 2025-11-03 19:37

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_delete_pricechartingintegration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricechartingconnect',
            name='current',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='pricechartingconnect',
            name='history',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
