server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.10.10.182:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets: [localhost]
        labels:
          host: "10.10.10.104"
          app: "collection"
          job: "docker"
          __path__: /var/lib/docker/containers/*/*-json.log
