# Generated by Django 4.2.25 on 2025-10-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='no description', max_length=700),
            preserve_default=False,
        ),
    ]
