# Generated by Django 4.2.25 on 2025-10-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='No description', max_length=700),
        ),
    ]
