# Generated by Django 4.2.25 on 2025-11-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('collection', '0003_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pricecharting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='games.pricechartingintegration'),
        ),
    ]
