# Generated by Django 4.2.25 on 2025-11-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="follow",
            name="accounts_fo_followe_7c063a_idx",
        ),
        migrations.RemoveIndex(
            model_name="follow",
            name="accounts_fo_followi_b590bd_idx",
        ),
    ]
