# Generated by Django 4.2.25 on 2025-12-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_follow_is_active_profile_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_md",
            field=models.ImageField(blank=True, editable=False, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_sm",
            field=models.ImageField(blank=True, editable=False, null=True, upload_to="avatars/"),
        ),
    ]
