# Generated by Django 4.2.25 on 2025-10-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='postimage',
            name='posts_posti_post_id_41c1fd_idx',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='order',
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post', 'id'], name='posts_posti_post_id_3169bd_idx'),
        ),
    ]
