# Generated by Django 4.2.25 on 2025-11-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="body",
        ),
        migrations.RemoveField(
            model_name="post",
            name="body",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
