# Generated by Django 4.2.25 on 2025-11-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_comment_body_remove_post_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
