# Generated by Django 4.2.25 on 2025-12-14 14:57

from django.db import migrations, models

import apps.posts.models.image


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_comment_is_active_commentreaction_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="preview_md",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=apps.posts.models.image.post_image_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="postimage",
            name="preview_sm",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=apps.posts.models.image.post_image_upload_to,
            ),
        ),
    ]
